# полная настройка, где все сервисы


services:
  # Базы данных

  # AUTH SERVICE
  postgres-auth:
    image: postgres:15
    container_name: restaurant-postgres-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5437:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    networks:
      - restaurant-network
    healthcheck:      # проверяет, жив ли контейнер (не просто запущен, а реально работает)
      test: [ "CMD-SHELL", "pg_isready -U postgres -d authdb" ]
      # pg_isready - утилита PostgreSQL, которая проверяет, готова ли БД
      #   -U postgres - пользователь postgres
      #   -d authdb  - база данных authdb
      # Возвращает:
      #   0 - БД готова к работе
      #   1 - БД не готова
      interval: 10s   # Каждые 10 секунд Docker запускает проверку
      timeout: 5s     # Ждём ответа 5 секунд (если дольше - считаем failed)
      retries: 5      # После 5 неудачных проверок подряд → контейнер unhealthy

  # ORDER SERVICE
  postgres-order:
    image: postgres:15
    container_name: restaurant-postgres-order
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    networks:
      - restaurant-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d orderdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # KITCHEN SERVICE
  postgres-kitchen:
    image: postgres:15
    container_name: restaurant-postgres-kitchen
    environment:
      POSTGRES_DB: kitchendb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-kitchen-data:/var/lib/postgresql/data
    networks:
      - restaurant-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d kitchendb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # PAYMENT SERVICE
  postgres-payment:
    image: postgres:15
    container_name: restaurant-postgres-payment
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data
    networks:
      - restaurant-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d paymentdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ------------ // ------------
  # REDIS (КЭШ)
  # Используется как: кэш, брокер сообщений, база данных для временных данных
  # REDIS (КЭШ)
  redis:
    image: redis:7-alpine
    container_name: restaurant-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - restaurant-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # KAFKA (БРОКЕР СООБЩЕНИЙ)
  #zookeeper:
  #  image: confluentinc/cp-zookeeper:latest
  #  container_name: restaurant-zookeeper
  #  environment:
  #    ZOOKEEPER_CLIENT_PORT: 2181
  #    ZOOKEEPER_TICK_TIME: 2000
  #  ports:
  #    - "2181:2181"
  #  networks:
  #    - restaurant-network
  #  healthcheck:
  #    test: [ "CMD", "nc", "-z", "localhost", "2181" ]
  #    interval: 10s
  #    timeout: 5s
  #    retries: 5


  kafka:
    image: confluentinc/cp-kafka:7.4.0  # latest — последняя версия с поддержкой KRaft
    container_name: restaurant-kafka
    ports:
      - "9092:9092"  # Для подключения с хоста
      - "29092:29092"  # Для подключения внутри Docker сети

    environment:
      # ОСНОВНЫЕ НАСТРОЙКИ KRaft
      # Роли брокера: broker (обрабатывает сообщения) + controller (управляет кластером)
      KAFKA_PROCESS_ROLES: broker,controller

      # Уникальный ID этого узла в кластере (один брокер, поэтому ID=1)
      KAFKA_NODE_ID: 1

      # Кворум контроллеров: список всех узлов-контроллеров в формате ID@хост:порт
      # 1@kafka:9093 - узел с ID=1 доступен внутри Docker сети по имени kafka на порту 9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # === НАСТРОЙКИ СЕТИ И СЛУШАТЕЛЕЙ ===
      # Слушатели: на каких адресах и портах Kafka принимает соединения
      # PLAINTEXT://0.0.0.0:9092 - для внешних подключений (с хоста)
      # CONTROLLER://0.0.0.0:9093 - для внутренних RPC вызовов между контроллерами
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093

      # Рекламируемые слушатели: какие адреса сообщать клиентам
      # localhost:9092 - для подключения с вашей хост-машины (вне Docker)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092

      # Соответствие между именами слушателей и протоколами безопасности
      # PLAINTEXT - незашифрованное соединение (для разработки)
      # CONTROLLER - внутренний протокол контроллеров (тоже PLAINTEXT для простоты)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Какой слушатель использовать для межконтроллерного общения
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # ХРАНЕНИЕ ДАННЫХ
      # Где хранить логи (сообщения) и метаданные
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # === НАСТРОЙКИ ДЛЯ РАЗРАБОТКИ (ОДИНОЧНЫЙ БРОКЕР) ===
      # Фактор репликации для внутренних топиков (1 - значит без репликации)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1


      #  ДОПОЛНИТЕЛЬНО: ОТКЛЮЧАЕМ ПРОВЕРКУ ПОЛИТИК (ДЛЯ РАЗРАБОТКИ)
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true  # Автоматически создавать топики при отправке сообщений

      # ОЧЕНЬ ВАЖНО для KRaft: инициализация кластера
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"  # Уникальный ID кластера (можно любой)
    networks:
      - restaurant-network
    volumes:
      - kafka-data:/var/lib/kafka/data  # для персистентности
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s


  # Kafka UI (для просмотра сообщений)
  # Настройка Веб-интерфейса, который позволяет видеть все сообщения в Kafka без командной строки.
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: restaurant-kafka-ui
    ports:
      - "8085:8080"
      # Локальный порт:8085 → порт контейнера:8080
      # Открываешь в браузере: http://localhost:8085
    environment:
      # Настройка первого кластера Kafka
      KAFKA_CLUSTERS_0_NAME: local
      # Имя кластера (показывается в UI)

      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      # Адрес Kafka внутри Docker сети
      # kafka - имя сервиса в docker-compose
      # 29092 - internal порт (для общения внутри Docker)


    networks:
      - restaurant-network
    depends_on:
      - kafka



  # PGADMIN (для просмотра БД)
  pgadmin:
    image: dpage/pgadmin4:latest
    # dpage/pgadmin4 - официальный образ PGAdmin
    # :latest - последняя версия
    container_name: restaurant-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@restaurant.com
      # Логин для входа в PGAdmin (email)
      PGADMIN_DEFAULT_PASSWORD: admin
      # Пароль для входа

    ports:
      - "5050:80"
    # Локальный порт:5050 → порт контейнера:80
    # Открываешь в браузере: http://localhost:5050
    networks:
      - restaurant-network
    depends_on:
      - postgres-auth
      - postgres-order
      - postgres-kitchen
      - postgres-payment
      # Ждёт, пока все БД запустятся

  # ------------ // ------------
  # МИКРОСЕРВИСЫ

  # ------------ // ------------
  # DISCOVERY SERVICE (EUREKA SERVER)
  # Discovery Service — это сервис обнаружения
  discovery-service:
    build: ./services/discovery-service # От куда собирается Docker образ
    ports:
      - "8761:8761"
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker # Spring Boot будет использовать application-docker.yml
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_CLOUD_CONFIG_FAIL_FAST: false
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    networks:
      - restaurant-network
    #healthcheck:
     # test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
     # interval: 10s
     # timeout: 5s
     # retries: 10

  # ------------ // ------------
  # CONFIG SERVICE (SPRING CLOUD CONFIG)
  # Config Service — это централизованный сервер конфигураций, который хранит все настройки
  #  всех микросервисов в одном месте
  config-service:
    build: ./services/config-service
    # Docker строит образ из исходников в папке ./services/config-service
    # Spring Boot приложение с @EnableConfigServer
    # @EnableConfigServer  //  Эта аннотация делает приложение Config Server!
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
      # Config Service запускается ПОСЛЕ Discovery Service
    environment:
      SPRING_PROFILES_ACTIVE: docker,native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:///config-repo
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    volumes:
      - ./infrastructure/config-repo:/config-repo
    networks:
      - restaurant-network
    #healthcheck:
      #test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      #interval: 10s
      #timeout: 5s
      #retries: 10

  # ------------ // ------------
  # API GATEWAY
  # API Gateway — это единая точка входа для всех клиентов
  gateway-service:
    build: ./services/gateway-service
    # Docker строит образ из исходников в папке ./services/gateway-service
    ports:
      - "8090:8090"
    env_file:
      - ./.env
    depends_on:
      - discovery-service
      - config-service
      - auth-service
      - order-service
      - kitchen-service
      - payment-service
      - notification-service
      # Запускается после этих сервисов
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-service:8888 # откуда брать конфигурацию
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_CLOUD_CONFIG_FAIL_FAST: false
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    networks:
      - restaurant-network



  # СЕРВИСЫ

  # ------------ // ------------
  # AUTH SERVICE
  auth-service:
    build: ./services/auth-service
    container_name: restaurant-auth-service
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_URL: http://config-service:8888
      SPRING_CLOUD_CONFIG_ENABLED: true
      SPRING_MAIN_WEB_APPLICATION_TYPE: servlet
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_CLIENT_ENABLED: true
      #redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 4
    networks:
      - restaurant-network
    depends_on:
    - discovery-service
    - config-service
    - postgres-auth
    - kafka
    - redis


  # ------------ // ------------
  # NOTIFICATION SERVICE
  notification-service:
    build: ./services/notification-service
    container_name: restaurant-notification-service
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      #redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 3
    networks:
      - restaurant-network
    depends_on:
      - discovery-service
      - config-service
      - kafka
      - redis


  # ------------ // ------------
  # ORDER SERVICE
  order-service:
    build: ./services/order-service
    container_name: restaurant-order-service
    ports:
      - "8082:8082"
      - "5005:5005"    # для отладки
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_URL: http://config-service:8888
      # для отладки
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"

      SPRING_CLOUD_CONFIG_ENABLED: true
      SPRING_MAIN_WEB_APPLICATION_TYPE: servlet
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_CLIENT_ENABLED: true
      #redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 5

    networks:
      - restaurant-network
    depends_on:
      - discovery-service
      - config-service
      - postgres-order
      - kafka
      - redis


  # ------------ // ------------
  # KITCHEN SERVICE
  kitchen-service:
    build: ./services/kitchen-service
    container_name: restaurant-kitchen-service
    ports:
      - "8083:8083"
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_CLOUD_CONFIG_FAIL_FAST: false
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      #redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 2

    networks:
      - restaurant-network
    depends_on:
      - discovery-service
      - config-service
      - postgres-kitchen
      - kafka
      - redis

  # ------------ // ------------
  # PAYMENT SERVICE
  payment-service:
    build: ./services/payment-service
    container_name: restaurant-payment-service
    ports:
      - "8084:8084"
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_CLOUD_CONFIG_FAIL_FAST: false
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      #redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 1
    networks:
      - restaurant-network
    depends_on:
      - discovery-service
      - config-service
      - postgres-payment
      - kafka
      - redis

  # MONITORING МОНИТОРИНГ

  prometheus:
    image: prom/prometheus:latest
    container_name: restaurant-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infrastructure/monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - ./infrastructure/monitoring/prometheus/rules.yml:/etc/prometheus/rules.yml:ro
      - prometheus-data:/prometheus
    networks:
      - restaurant-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # GRAFANA
  grafana:
    image: grafana/grafana:latest
    container_name: restaurant-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infrastructure/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infrastructure/monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./infrastructure/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    networks:
      - restaurant-network
    depends_on:
      - prometheus
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # JAEGER
  jaeger:
    image: jaegertracing/jaeger:latest # Или зафиксируйте версию: 2.15.0
    container_name: restaurant-jaeger
    ports:
      # UI и API
      - "16686:16686"
      # Zipkin API (для Spring Boot)
      - "9411:9411"
      # OTLP (OpenTelemetry) для современных клиентов
      - "4317:4317"   # gRPC
      - "4318:4318"   # HTTP
    environment:
      # Используем память для хранения (быстро и без прав)
      - JAEGER_STORAGE_TYPE=memory
      # Включаем все коллекторы
      - JAEGER_COLLECTOR_OTLP_ENABLED=true
      - JAEGER_OTLP_HOST=0.0.0.0
    networks:
      - restaurant-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:16686/api/services" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

# СЕТИ
networks:
  restaurant-network:
    driver: bridge
    # Bridge — стандартный драйвер сети Docker
    #Создает изолированную виртуальную сеть на одном хосте
    #Контейнеры в bridge сети могут общаться друг с другом
    #Контейнеры изолированы от других сетей

# ------------ // ------------
# ТОМА (ПЕРСИСТЕНТНОСТЬ ДАННЫХ)
volumes:
  # Docker Volumes — это механизм постоянного хранения данных, который позволяет
  # сохранять информацию даже после удаления и пересоздания контейнеров

  # Ключевые моменты:
  # Тома сохраняют данные при перезапуске контейнеров
  # Каждая БД имеет свой изолированный том
  #Тома не удаляются при docker-compose down (без -v)
  #Данные хранятся в /var/lib/docker/volumes/ на хосте
  postgres-auth-data:
  postgres-order-data:
  postgres-kitchen-data:
  postgres-payment-data:
  redis-data:
  kafka-data:
  prometheus-data:
  grafana-data:
  jaeger-data:

  # Правильный порядок запуска:
  #1. discovery-service  (Eureka)  # Eureka (чтобы найти другие сервисы)
  #2. config-service     (Config)  # Config Server (чтобы получить конфигурацию)
  #3. gateway-service    (Gateway) # Потом шлюз, после всех зависимостей
  #4. auth-service       (Auth)    # Потом бизнес-сервисы
  #5. order-service      (Order)
  #6. kitchen-service    (Kitchen)
  #7. payment-service    (Payment)
  ## Без Eureka Config Service не может зарегистрироваться
  ## Без Config Service другие сервисы не получат конфиги
