# ПЕРЕОПРЕДЕЛЯЕТ настройки из application.yml
# SPRING_PROFILES_ACTIVE=dev
# Используется, когда запускаем сервис ЛОКАЛЬНО (не в Docker)


spring:
  config:
    activate:
      on-profile: dev   # Активируется только для профиля dev


  # Отключаем Config Server для локальной разработки
  cloud:
    config:
      enabled: false


  # Настройки БД (локальный PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: postgres
    password: postgres
    #password: user
    driver-class-name: org.postgresql.Driver

  # JPA настройки
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  # Для локальной разработки используем localhost
  kafka:
    bootstrap-servers: localhost:9092   # Кафка на локальной машине
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"



  data:
    redis:
      host: localhost                    # Redis на локальной машине
      port: 6379
      database: 0


# Server port
server:
  port: 8082


# Для локальной разработки Eureka тоже на localhost
eureka:
  client:
    enabled: false
    #service-url:
      #defaultZone: http://localhost:8761/eureka/

# В dev режиме включаем DEBUG логи
logging:
  level:
    com.restaurant: DEBUG               # Сервисы
    org.hibernate.SQL: DEBUG            # SQL запросы Hibernate
    org.springframework.kafka: DEBUG    # Kafka сообщения
    org.springframework.web: DEBUG
      # Hibernate типы данных (показывает значения параметров)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


#PROMETHEUS & METRICS
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,httptrace
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: dev  # ← Фиксируем окружение

  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: w3c, b3, b3_multi
      produce: w3c, b3
    baggage:
      enabled: true
    log:
      slf4j:
        enabled: true
    mdc:
      enabled: true
      fields:
        - traceId
        - spanId
        - parentId
        - applicationName
        - instanceId

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans  # Jaeger локально