# Eureka Server - реестр всех микросервисов
# Все сервисы регистрируются здесь, чтобы находить друг друга


server:
  # Здесь находится веб-интерфейс для просмотра зарегистрированных сервисов
  port: 8761
    # Порт, на котором будет запущен Eureka Server
    # 8761 - стандартный порт для Eureka


eureka:
  client:
    # register-with-eureka: регистрировать ли этот сервер в Eureka

    # false - НЕ регистрировать себя как клиента
    # Почему false? Eureka Server сам является реестром, ему не нужно
    # регистрироваться у самого себя (иначе получится рекурсия)

    # true - используется, если у вас кластер из нескольких Eureka серверов, чтобы они регистрировались друг у друга

    # Если бы было true (как у обычных микросервисов):
    # Eureka Server пытается зарегистрироваться сам у себя

    # В логах будет:
    # "Registered instance DISCOVERY-SERVICE/localhost:8761"

    # В веб-интерфейсе будет:
    # DISCOVERY-SERVICE (1) ← сам себя видит

    # В режиме когда один сервер это не нужно и создает лишнюю сущность
    register-with-eureka: false


    # fetch-registry: скачивать ли реестр с других Eureka серверов
    # false - НЕ скачивать реестр
    # Так как Это единственный Eureka сервер (не кластер), ему неоткуда скачивать реестр

    # true - используется в кластере, чтобы синхронизировать реестры

    # Если бы было true:
    # Eureka Server пытается скачать реестр с других Eureka серверов
    # Но так как других нет (или они не указаны), это бессмысленно
    # Может вызывать ошибки в логах:
    # "Unable to fetch registry from any replica"

    # В кластере из нескольких Eureka серверов:
    # - register-with-eureka: true  (регистрируются друг у друга)
    # - fetch-registry: true (синхронизируют реестры)

    fetch-registry: false
  server:
    # enable-self-preservation: режим самосохранения Eureka
    # false - ОТКЛЮЧИТЬ режим самосохранения

    # Что такое режим самосохранения (self-preservation)?
    # По умолчанию (true) Eureka включает защитный механизм:
    # - Если более 85% клиентов перестали присылать heartbeat (сигналы "я жив")
    # - Eureka НЕ удаляет "мертвые" сервисы из реестра
    # - Предполагается, что проблема в сети, а не в сервисах
    # - Защищает от "лавинной" разерегистрации всех сервисов

    # Режим самосохранения ОТКЛЮЧЕН (false):

    # Время: 10:00 - все 10 сервисов работают
    # Время: 10:05 - проблема с сетью, 8 сервисов перестали отвечать
    # Eureka: "Прошло 90 секунд, heartbeat нет → удаляю сервисы"

    # Результат:
    # - В реестре осталось 2 сервиса
    # - Gateway видит только живые сервисы
    # - Запросы не падают (так как не маршрутизируются на мертвые)

    # отключаем, чтобы сразу видеть падения
    enable-self-preservation: false