
server:
  port: 8082

spring:
  application:
    name: order-service
  
  datasource:
    url: jdbc:postgresql://postgres-order:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # ИНДИВИДУАЛЬНЫЕ KAFKA НАСТРОЙКИ
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: order-group   # Группа для балансировки нагрузки

# специфичны для Order Service
app:
  kafka:
    topics:
      order-created: order-service.order.created    # Топик "заказ создан"
      order-paid: order-service.order.paid          # Топик "заказ оплачен"
      order-cancelled: order-service.order.cancelled

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}