
server:
  port: 8082

spring:
  application:
    name: order-service
  
  datasource:
    url: jdbc:postgresql://postgres-order:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    # Метрики Hikari
    hikari:
      pool-name: order-service-pool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1800000
      register-mbeans: true
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # ИНДИВИДУАЛЬНЫЕ KAFKA НАСТРОЙКИ
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: order-group   # Группа для балансировки нагрузки

# Добавляем management Hikari
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      hikaricp: true
      jdbc: true
    tags:
      service: order-service

# специфичны для Order Service
app:
  kafka:
    topics:
      order-created: order-service.order.created    # Топик "заказ создан"
      order-paid: order-service.order.paid          # Топик "заказ оплачен"
      order-cancelled: order-service.order.cancelled

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}