
server:
  port: 8084

spring:
  application:
    name: payment-service
  
  datasource:
    url: jdbc:postgresql://postgres-payment:5432/paymentdb
    username: ${PAYMENT_DB_USER:postgres}
    password: ${PAYMENT_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
  
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: payment-group

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}

payment:
  max-amount: 10000       # Максимальная сумма для успешного платежа
  delay-ms: 2000          # Симуляция задержки платежной системы