{
 "title": "Quick Overview",
 "tags": [
  "overview",
  "simple"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Order Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"order-service\"}",
     "legendFormat": "Order"
    }
   ]
  },
  {
   "title": "Auth Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"auth-service\"}",
     "legendFormat": "Auth"
    }
   ]
  },
  {
   "title": "Kitchen Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"kitchen-service\"}",
     "legendFormat": "Kitchen"
    }
   ]
  },
  {
   "title": "Payment Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"payment-service\"}",
     "legendFormat": "Payment"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"gateway-service\"}",
     "legendFormat": "Gateway"
    }
   ]
  },
  {
   "title": "Config Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"config-service\"}",
     "legendFormat": "Config"
    }
   ]
  },
  {
   "title": "Discovery",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"discovery-service\"}",
     "legendFormat": "Discovery"
    }
   ]
  },
  {
   "title": "Запросы в минуту по сервисам",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Сообщения из Kafka в минуту",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(kafka_messages_consumed_total[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}