server:
  port: 8090

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
              filters:
                - AddRequestHeader=X-Request-Source, gateway
            - id: order-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/orders/**
              filters:
                - AddRequestHeader=X-Request-Source, gateway
            - id: kitchen-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/kitchen/**
              filters:
                - AddRequestHeader=X-Request-Source, gateway
            - id: payment-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/payment/**
              filters:
                - AddRequestHeader=X-Request-Source, gateway
            - id: notification-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/notification/**
              filters:
                - AddRequestHeader=X-Request-Source, gateway

eureka:
  client:
    enabled: false

#  PROMETHEUS & METRICS
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway,routes
      base-path: /actuator
  metrics:
    tags:
      application: gateway-service
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.restaurant.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG