spring:
  main:
    web-application-type: reactive

logging:
  level:
    com.restaurant.gateway: DEBUG
    org.springframework.cloud.gateway: INFO

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      authService:
        baseConfig: default