spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:docker}
  
  config:
    # Используем переменную окружения для URI Config Server'а
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-service:8888}