# Профиль "docker" (SPRING_PROFILES_ACTIVE=docker)
# Используется, когда сервисы запущены в Docker-контейнерах


spring:
  config:
    activate:
      on-profile: docker

  # В Docker сети обращаемся к контейнеру по его имени
  kafka:
    bootstrap-servers: kafka:9092        # Контейнер с именем "kafka"

  data:
    redis:
      host: redis                         # Контейнер с именем "redis"

# Eureka тоже в Docker контейнере
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/