server:
  port: 8083

spring:
  application:
    name: kitchen-service
  
  datasource:
    url: jdbc:postgresql://postgres-kitchen:5432/kitchendb
    username: ${KITCHEN_DB_USER:postgres}
    password: ${KITCHEN_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
      default_schema: kitchen_schema
  
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: kitchen-group

app:
  kafka:
    topics:
      order-created: order-service.order.created         # Топик "заказ создан"
      order-paid: order-service.order.paid               # Топик "заказ оплачен"
      kitchen-order-ready: kitchen-service.kitchen.order.ready